### ISSUE TITLE
2.4.0: default to qt5, implement USE=qt6?

### ISSUE THREAD

**Issue by lkraav** [jaakristioja/web-eid#2]
https://github.com/web-eid/web-eid-app#internal-design at least at 2.4.0 time states "compatible with both Qt5 and Qt6".

This is the first qt6 package on my systems... creates a bunch of extra Qt6 build work for just web-eid-app. Maybe too early to default to Qt6? I know it's an extra lift, and I'm not sure how heavy. Your thoughts?

**Comment by jaakristioja** [comment]
I don't think it is too early. The sooner we get rid of Qt5 the better. Adding support for both Qt5 and Qt6 is difficult and time consuming (especially testing it) and not worth the effort. Qt6 is stable enough and can be installed in parallel so the only win would probably be in slightly less disk usage and faster install times when one only has Qt5 installed.

I don't plan to implement this. Closing.
